### ISSUE TITLE
backpressure-demo "queue full?!" exception with concatMap

### ISSUE THREAD

**Issue by cederigo** [salesforce/reactive-grpc#120]
Instead of using
```java
.zipWith(Flowable.interval(3, TimeUnit.MILLISECONDS), (item, interval) -> item)
```
to simulate a slow consumer, I tried
```java
.concatMap(item -> Flowable.just(item).delay(3, TimeUnit.MILLISECONDS))
```
to reproduce the "queue full?!" error [1] we encountered in our project. I can get around the issue using `rebatchRequests(1024)` before `concatMap` but I dont understand exactly why `concatMap` does not work without it.

I'm aware that this issue is maybe not directly related to this project but I would be very grateful for any answers/hints that help me bring some light into the dark.

Cheers, Cédric

Link to demo: https://github.com/salesforce/reactive-grpc/blob/master/demos/backpressure-demo/src/main/java/demo/backpressure/BackpressureController.java#L57
[1] Full stack trace:
```java
java.lang.IllegalStateException: Queue full?!
	at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:155)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
	at com.salesforce.rxgrpc.stub.SubscribeOnlyOnceFlowableOperator$1.onNext(SubscribeOnlyOnceFlowableOperator.java:41)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at com.salesforce.reactivegrpc.common.ReactiveBackpressureChunker$1.onNext(ReactiveBackpressureChunker.java:71)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at com.salesforce.reactivegrpc.common.ReactiveStreamObserverPublisherBase.onNext(ReactiveStreamObserverPublisherBase.java:106)
	at com.salesforce.reactivegrpc.common.ReactiveStreamObserverPublisherClient.onNext(ReactiveStreamObserverPublisherClient.java:51)
	at com.salesforce.reactivegrpc.common.ReactiveConsumerStreamObserver.onNext(ReactiveConsumerStreamObserver.java:52)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:406)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:526)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rmichela** [comment]
Thanks for the report. Here is what I _think_ is happening (reasoning about async RxJava can be tricky).

`.zipWith(Flowable.interval(3, TimeUnit.MILLISECONDS), (item, interval) -> item)` combines the fast stream from `sendNumbers` with a stream that emits a new item every three milliseconds. The zip operator will only emit a tuple event when both zipped flowables have an event ready, and will applybackpressure upstream when waiting.

`.concatMap(item -> Flowable.just(item).delay(3, TimeUnit.MILLISECONDS))` consumes each item from the fast `sendNumbers` stream and delays it by three milliseconds.

If I understand what is happening correctly, `zipWith` acts like a "serial" delay, while `concatMap` acts like a "parallel" delay. The output of `concatMap` emits items at the same rate as its input, with each item time shifted by three milliseconds. 

The next operator in the chain is an `observeOn`, which uses an internal buffer to hold items between threads. The fast "time shifted" stream from `zipWith` overwhelms this buffer, resulting in the `Queue full?!` exception.

**Comment by cbornet** [comment]
Does it mean that concatMap doesn't respect backpressure / consumer pull-mode ?

**Comment by rmichela** [comment]
[`concatMap()`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#concatMap-io.reactivex.functions.Function-) - The operator honors backpressure from downstream. Both this and the inner Publishers are expected to honor backpressure as well. If the source Publisher violates the rule, the operator will signal a MissingBackpressureException. If any of the inner Publishers doesn't honor backpressure, that may throw an IllegalStateException when that Publisher completes.

[`delay()`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#observeOn-io.reactivex.Scheduler-) - The operator doesn't interfere with the backpressure behavior which is determined by the source Publisher. All of the other Publishers supplied by the function are consumed in an unbounded manner (i.e., no backpressure applied to them).

It's possible the `delay()` is interfering with `concatMap()`'s expectation that all inner publishers honor backpressure.

**Comment by rmichela** [comment]
@cbornet Tell me about it 😕 

@cederigo Are you able to reproduce this problem in isolation?

**Comment by Lemutar** [comment]
If you replace the 
`.zipWith(Flowable.interval(3, TimeUnit.MILLISECONDS), (item, interval) -> item)`
with
`.concatMap(item -> Flowable.just(item).delay(3, TimeUnit.MILLISECONDS))`
in [BackpressureController](https://github.com/salesforce/reactive-grpc/blob/master/demos/backpressure-demo/src/main/java/demo/backpressure/BackpressureController.java#L57) you will be able to reproduce the problem. 

After analyzing the problem a little it seems the problem is caused by [ReactiveBackpressureChunker](https://github.com/salesforce/reactive-grpc/blob/master/common/reactive-grpc-common/src/main/java/com/salesforce/reactivegrpc/common/ReactiveBackpressureChunker.java).

concatMap is picky about buffer size, this means:
  if concatMap maps request 2 elements and get 16 it will throw a "Queue full?!" error.

If I'm not wrong this is what we see:
  concatMap request 2 elements.
  ReactiveBackpressureChunker gets the request and requests 16 by its own.
  ReactiveBackpressureChunker sends all these 16 elements downstream what causes concatMap to throw the error.

We may could solve this issue by buffer the elements in ReactiveBackpressureChunker. So requesting 16 upstream but sending (in this case) two downstream and buffer the rest. As soon the buffer runs low request another 16.

**Comment by cederigo** [comment]
Thank you all for your answers. Really appreciate it! 

@Lemutar nice find! Thats exactly how I reproduced it in isolation and a colleague of mine also had the suspicion that the concatMap operator gets more elements than it requested. If we could solve this issue as @Lemutar suggested that would be amazing. Otherwise, there should be a section in the Readme because it is really not obvious that one can not use a slow `concatMap` without `rebatchRequests(..)`.

Btw.: The error can also be reproduced with `flatMap`..
