### ISSUE TITLE
Release a ready to run rxgrpc generator

### ISSUE THREAD

**Issue by frankbenoit** [salesforce/reactive-grpc#163]
At the moment there is a protococ-gen-rxgrpc.exe, that uses a .ini which contains local paths to maven cache jars.

````
vm.location=c:\...\jre\bin\server\jvm.dll
classpath.1=C:\Users\username\.m2\repository\com\salesforce\servicelibs\rxgrpc\0.9.0\rxgrpc-0.9.0.jar
classpath.2=C:\Users\username\.m2\repository\com\salesforce\servicelibs\reactive-grpc-gencommon\0.9.0\reactive-grpc-gencommon-0.9.0.jar
classpath.3=C:\Users\username\.m2\repository\com\salesforce\servicelibs\grpc-contrib\0.8.0\grpc-contrib-0.8.0.jar
classpath.4=C:\Users\username\.m2\repository\io\grpc\grpc-core\1.10.0\grpc-core-1.10.0.jar
classpath.5=C:\Users\username\.m2\repository\io\grpc\grpc-context\1.10.0\grpc-context-1.10.0.jar
classpath.6=C:\Users\username\.m2\repository\com\google\code\gson\gson\2.7\gson-2.7.jar
classpath.7=C:\Users\username\.m2\repository\com\google\guava\guava\19.0\guava-19.0.jar
classpath.8=C:\Users\username\.m2\repository\com\google\errorprone\error_prone_annotations\2.1.2\error_prone_annotations-2.1.2.jar
classpath.9=C:\Users\username\.m2\repository\com\google\code\findbugs\jsr305\3.0.0\jsr305-3.0.0.jar
classpath.10=C:\Users\username\.m2\repository\io\opencensus\opencensus-api\0.11.0\opencensus-api-0.11.0.jar
classpath.11=C:\Users\username\.m2\repository\io\opencensus\opencensus-contrib-grpc-metrics\0.11.0\opencensus-contrib-grpc-metrics-0.11.0.jar
classpath.12=C:\Users\username\.m2\repository\io\grpc\grpc-stub\1.10.0\grpc-stub-1.10.0.jar
classpath.13=C:\Users\username\.m2\repository\io\grpc\grpc-protobuf\1.10.0\grpc-protobuf-1.10.0.jar
classpath.14=C:\Users\username\.m2\repository\com\google\protobuf\protobuf-java\3.5.1\protobuf-java-3.5.1.jar
classpath.15=C:\Users\username\.m2\repository\com\google\protobuf\protobuf-java-util\3.5.1\protobuf-java-util-3.5.1.jar
classpath.16=C:\Users\username\.m2\repository\com\google\api\grpc\proto-google-common-protos\1.0.0\proto-google-common-protos-1.0.0.jar
classpath.17=C:\Users\username\.m2\repository\io\grpc\grpc-protobuf-lite\1.10.0\grpc-protobuf-lite-1.10.0.jar
classpath.18=C:\Users\username\.m2\repository\com\salesforce\servicelibs\jprotoc\0.8.0\jprotoc-0.8.0.jar
classpath.19=C:\Users\username\.m2\repository\com\github\spullara\mustache\java\compiler\0.9.4\compiler-0.9.4.jar
main.class=com.salesforce.rxgrpc.RxGrpcGenerator
vm.version.min=1.6
log.level=none
[ErrorMessages]
show.popup=false
````

Can it be packed into something that i can put into a repository and just execute without the need for a specific build tool?  

As it is, i cannot put this into a repository with a batch file to execute. On a different PC without maven running before, or a different username, this will fail with:
````
java.lang.NoClassDefFoundError: com/salesforce/rxgrpc/RxGrpcGenerator
Caused by: java.lang.ClassNotFoundException: com.salesforce.rxgrpc.RxGrpcGenerator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
````

Like the grpc generator is a downloadable .exe.  
In fact I want to call it manually.

thanks
Frank

**Comment by rmichela** [comment]
Are you using some kind of java exe wrapper here?

**Comment by frankbenoit** [comment]
After building the demo applications with maven, I found target/protoc-plugins/protoc-gen-rxgrpc.exe and tried to add it into my existing project.  
This worked locally. But after test on another PC, it failed.

**Comment by rmichela** [comment]
I see. That's an intermediate file generated by the `maven-protobuf-plugin` for executing the plugin on windows.

Protoc plugins aren't really made to be run as stand-alone executables.

**Comment by frankbenoit** [comment]
Yes, maven might use this technic. 
When I am working with GRPC Java, I can build a command on my own and execute it independent from a specific build system, because the is a .exe available.

Can this be done for reactive-grpc as well?

**Comment by rmichela** [comment]
What you are asking for is not easy to support on Windows today. 😕
