### ISSUE TITLE
[reactor-grpc] Reactor context does not propagate if stub is used

### ISSUE THREAD

**Issue by krakowski** [salesforce/reactive-grpc#195]
Description
--

Whenever a stub is used in a chain together with Reactor's [Context API](https://projectreactor.io/docs/core/release/reference/#_the_context_api) the provided context does not propagate correctly. My guess is, that using `subscribe()` within [ClientCalls](https://github.com/salesforce/reactive-grpc/blob/2b571218655674450ddd0b45af38b5bb0afd0915/reactor/reactor-grpc-stub/src/main/java/com/salesforce/reactorgrpc/stub/ClientCalls.java) is preventing the context from propagating up the chain.

Example
--

```java
package com.salesforce.reactorgrpc;

import com.salesforce.grpc.testing.contrib.NettyGrpcServerRule;
import org.junit.Rule;
import org.junit.Test;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;
import reactor.util.context.Context;

import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;

public class ReactorContextPropagationTest {

    @Rule
    public NettyGrpcServerRule serverRule = new NettyGrpcServerRule();

    private static class SimpleGreeter extends ReactorGreeterGrpc.GreeterImplBase {
        @Override
        public Mono<HelloResponse> sayHello(Mono<HelloRequest> request) {
            return request.map(HelloRequest::getName)
                    .map(name -> HelloResponse.newBuilder().setMessage("Hello " + name).build());
        }

        @Override
        public Mono<HelloResponse> sayHelloReqStream(Flux<HelloRequest> request) {
            return request.map(HelloRequest::getName)
                    .collect(Collectors.joining("and"))
                    .map(names -> HelloResponse.newBuilder().setMessage("Hello " + names).build());
        }
    }

    @Test
    public void contextDoesNotPropagate() {
        serverRule.getServiceRegistry().addService(new SimpleGreeter());

        ReactorGreeterGrpc.ReactorGreeterStub stub = ReactorGreeterGrpc.newReactorStub(serverRule.getChannel());
        Mono<HelloRequest> req = Mono.just(HelloRequest.newBuilder().setName("reactor").build());

        Mono<HelloResponse> resp = req
                // This assertion will fail 
                .doOnEach(signal -> assertThat(signal.getContext().getOrEmpty("key")).isNotEmpty())
                .compose(stub::sayHello)
                // This assertion won't fail
                .doOnEach(signal -> assertThat(signal.getContext().getOrEmpty("key")).isNotEmpty())
                .subscriberContext(Context.of("key", "dummy"));

        StepVerifier.create(resp)
                .expectNextMatches(response -> response.getMessage().equals("Hello reactor"))
                .verifyComplete();
    }
}
```

**Comment by krakowski** [comment]
I could fix this in the `one-to-one` case by using `flatMap` instead of `subscribe`, though I'm not sure if this is correct since I removed the `SubscribeOnlyOnceLifter`.

```java
return monoSource.flatMap(request -> Mono.create(callback -> {
    delegate.accept(request, new StreamObserver<TResponse>() {
        @Override
        public void onNext(TResponse tResponse) {
            callback.success(tResponse);
        }

        @Override
        public void onError(Throwable throwable) {
            callback.error(throwable);
        }

        @Override
        public void onCompleted() {
            // do nothing
        }
    });
}));
```

**Comment by krakowski** [comment]
I implemented a [failing test](https://github.com/krakowski/reactive-grpc/blob/c7eb05ea23bb9994334af7cc93b4c0c69dbe187d/reactor/reactor-grpc-test/src/test/java/com/salesforce/reactorgrpc/ReactorContextPropagationTest.java) for this issue.

  - `oneToMany` - :heavy_check_mark: 
  - `oneToOne` - :x: 
  - `manyToOne` - :x: 
  - `manyToMany` - :x:

**Comment by dyangelo-grullon** [comment]
@rmichela a team of mine is thinking of adopting this library, but it's concerning that this bug has been opened since October 2019 without a response from the maintainers. Is there any documentation on how to properly propagate the reactor context? Is this an actual bug?

**Comment by rmichela** [comment]
> Is there any documentation on how to properly propagate the reactor context? 
I've found the documentation and examples for using reactor context to be sorely lacking. 

> Is this an actual bug?
I'm not entirely sure. The absence of "me too" reports has me wondering if this is a real issue.

**Comment by rmichela** [comment]
Do you use reactor context? If so, are you experiencing this issue?

**Comment by rmichela** [comment]
Following up. Is this still an issue for you?

**Comment by krakowski** [comment]
Hi all,

just rebased [my tests from last year](https://github.com/krakowski/reactive-grpc/blob/test/195/reactor-context/reactor/reactor-grpc-test/src/test/java/com/salesforce/reactorgrpc/ReactorContextPropagationTest.java) on the current `master` branch and ran them again.

![tests](https://i.imgur.com/PUxd7Ec.png)

I use [Reactor's Context API](https://projectreactor.io/docs/core/release/reference/#context) to propagate metadata (e.g. JWT or tracing information) inside reactive sequences. Using the [gRPC Context API](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html) directly within reactive sequences is not possible for me, since the context is [stored within a ThreadLocal](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.Storage.html).

> The default implementation will put the current context in a ThreadLocal.

After switching threads the context would thus no longer be accessible.

I also tried to propagate tracing information between separate services over gRPC. For this purpose I wrote a [ClientInterceptor](https://grpc.github.io/grpc-java/javadoc/io/grpc/ClientInterceptor.html) which transfers tracing information between Reactor context and gRPC headers ([TracingInterceptor](https://github.com/hhu-educode/shared/blob/master/src/main/java/de/hhu/educode/shared/grpc/TracingInterceptor.java)). Unfortunately, accessing the Reactor context within the ClientInterceptor always yielded an empty Mono.

**Comment by krakowski** [comment]
Since I will most likely be using this library again in the near future, I took another look at the issue. Shortly after my last message last year, the following post was written regarding context loss detection, which discusses in which cases the Reactor context can be lost.

  * [Daily Reactive: Context loss detection in Project Reactor](https://bsideup.github.io/posts/daily_reactive/context_loss_detection/) by [Sergei Egorov](https://github.com/bsideup)
  
Basically, in case of a subscription, the context must be passed on via the [`CoreSubscriber#currentContext()`](https://projectreactor.io/docs/core/release/api/reactor/core/CoreSubscriber.html#currentContext--) method, otherwise the interface's default implementation takes effect, which returns an empty context.

In addition, there is a hook that detects the loss of a context and can be enabled using `Hooks.enableContextLossTracking();`.

Therefore, I think this issue could be solved easily by implementing the mentioned method in [ReactorSubscriberAndClientProducer](https://github.com/salesforce/reactive-grpc/blob/master/reactor/reactor-grpc-stub/src/main/java/com/salesforce/reactorgrpc/stub/ReactorSubscriberAndClientProducer.java),  [ReactorSubscriberAndServerProducer](https://github.com/salesforce/reactive-grpc/blob/master/reactor/reactor-grpc-stub/src/main/java/com/salesforce/reactorgrpc/stub/ReactorSubscriberAndServerProducer.java) and [SubscribeOnlyOnceLifter](https://github.com/salesforce/reactive-grpc/blob/master/reactor/reactor-grpc-stub/src/main/java/com/salesforce/reactorgrpc/stub/SubscribeOnlyOnceLifter.java).

@rmichela What do you think?

**Comment by Freddv2** [comment]
Hello, we're having the same issue here. Activating enableContextLossTracking() show that the context was lost at: 
```ClientCalls.oneToOne ... 
.transform(Operators.lift(new SubscribeOnlyOnceLifter<TResponse>()));
```


```java.lang.IllegalStateException: Context loss after applying reactor.core.publisher.Operators$LiftFunction@617af642
	at reactor.core.publisher.ContextTrackingFunctionWrapper.lambda$apply$0(ContextTrackingFunctionWrapper.java:50)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoLift] :
	reactor.core.publisher.Mono.transform(Mono.java:4705)
	com.salesforce.reactorgrpc.stub.ClientCalls.oneToOne(ClientCalls.java:57)
Error has been observed at the following site(s):
	|_     Mono.transform ⇢ at com.salesforce.reactorgrpc.stub.ClientCalls.oneToOne(ClientCalls.java:57)
```

**Comment by code-uri** [comment]
Hello everyone,

Any Update one this. any work around?

**Comment by code-uri** [comment]
Hello again,
I tried reproducing it but test is passing. am I missing something?

**Comment by code-uri** [comment]
I tried the test again using subscribeOn() the test failed.

**Comment by krakowski** [comment]
Hey @code-uri,

I rebased my tests from 3 years ago again on top of the current `master` to check if this was fixed (120 commits since then) and they still seem to fail. You can try out the tests in my personal branch which reproduces this issue.

  * https://github.com/krakowski/reactive-grpc/blob/test/195/reactor-context/reactor/reactor-grpc-test/src/test/java/com/salesforce/reactorgrpc/ReactorContextPropagationTest.java

In my case the results are the same as 3 years ago:

![Screenshot from 2022-11-04 13-29-45](https://user-images.githubusercontent.com/7255767/199973805-01675706-e85e-445b-8441-0d98e36e8c1f.png)


I haven't found any workaround for this issue.

**Comment by denychen** [comment]
Currently on version 1.2.4, and I'm running into this bug as well.

**Comment by rmichela** [comment]
I've got to be honest, I've tried my best with my he edge cases of Reactor context propagation, and its interactions with gRPC thread pools. But I'm out of my depth. 

I could really use some help with this issue.

**Comment by code-uri** [comment]
> I've got to be honest, I've tried my best with my he edge cases of Reactor context propagation, and its interactions with gRPC thread pools. But I'm out of my depth.
> 
> I could really use some help with this issue.

I agree that the context propagation is not working. Apart from the test case you mentioned, Could you explain the use case?
for example in my case I wanted to pass on the information to grpc layer to in the form of headers like this. I hope this will help.

```
 ReactorGreeterGrpc.ReactorGreeterStub targetStub = ...
    Mono<HelloRequest> req = Mono.just(HelloRequest.newBuilder().setName("reactor").build());
    req.flatMap(helloRequest -> {
        return Mono.deferContextual(contextView -> {
            Metadata header = new Metadata();
            Metadata.Key<String> key =
                    Metadata.Key.of("KEY", Metadata.ASCII_STRING_MARSHALLER);
            header.put(key, contextView.getOrDefault("key", "dummy"));


            targetStub = targetStub.withInterceptors(MetadataUtils.newAttachHeadersInterceptor(header));
            targetStub.sayHello(helloRequest);
        }
    }).contextWrite(context -> Context.of("key", "dummy")).block();          
```

**Comment by code-uri** [comment]
@rmichela  Also reactor now supports  ThreadLocal propagation magic you can use that aswell to read the values in from ThreadLocal in grpc layer.

**Comment by rmichela** [comment]
Is there a doc link you can point me to?
