### ISSUE TITLE
NPE in scheduler thread when use publishOn

### ISSUE THREAD

**Issue by cyberpunk2025** [salesforce/reactive-grpc#247]
Unit test to reproduce the NPE:

```
    @Test
    public void run() throws Exception {
        Semaphore sem = new Semaphore(0);
        for (int k = 0; k < 100; k++) {
            Flux<byte[]> inputs = Flux.create(sink -> {
                this.sink = sink;
            });

            inputs = inputs.publishOn(scheduler);

            Flux<VadGrpcRequest> requests = inputs
                .index((i, data) -> createVadRequest(i, data));

            ReactorVadGrpc.ReactorVadStub stub = vadStubFactory.getStub("11.164.194.181:16907");
            stub.process(requests)
                .doOnNext(res -> log.info("Response"))
                .doOnComplete(() -> {
                    log.info("Completed");
                    sem.release();
                })
                .subscribe();

            sink.next(new byte[1000]);
            sink.next(new byte[1000]);
            sink.next(new byte[1000]);
            sink.next(new byte[1000]);
            sink.next(new byte[1000]);
            sink.complete();

            sem.acquire();
        }
    }
```

The output is like this:

```
[20:32:02.470] Response
[20:32:02.475] Response
[20:32:02.475] Response
[20:32:02.475] Response
[20:32:02.475] Response
[20:32:02.475] Response
[20:32:02.476] Completed
[20:32:02.658] Response
[20:32:02.658] Response
[20:32:02.659] Response
[20:32:02.660] Response
[20:32:02.660] Response
[20:32:02.660] Response
[20:32:02.660] Completed
[20:32:02.819] Response
[20:32:02.821] Response
[20:32:02.821] Response
[20:32:02.822] Response
[20:32:02.822] Response
[20:32:02.823] Response
[20:32:02.823] Completed
[20:32:03.002] Response
[20:32:03.002] Response
[20:32:03.002] Response
[20:32:03.004] Response
[20:32:03.004] Response
[20:32:03.004] Response
[20:32:03.005] Completed
[20:32:03.014] Scheduler worker in group main failed with an uncaught exception
java.lang.NullPointerException: null
	at io.grpc.internal.ClientCallImpl.isReady(ClientCallImpl.java:569)
	at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.isReady(ClientCalls.java:381)
	at com.salesforce.reactivegrpc.common.AbstractSubscriberAndProducer.drainAsync(AbstractSubscriberAndProducer.java:323)
	at com.salesforce.reactivegrpc.common.AbstractSubscriberAndProducer.drain(AbstractSubscriberAndProducer.java:226)
	at com.salesforce.reactivegrpc.common.AbstractSubscriberAndProducer.onNext(AbstractSubscriberAndProducer.java:146)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.onNext(FluxIndexFuseable.java:122)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runBackfused(FluxPublishOn.java:483)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:520)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by rmichela** [comment]
Not reproducible - closing
