### ISSUE TITLE
Error signal not propagated because canceling subscription throws exception

### ISSUE THREAD

**Issue by tukez** [salesforce/reactive-grpc#68]
Note: I'm not entirely sure is the problem on grpc, reactive-grpc, or even reactor side. Let's see what you guys think...

Stack trace:
```
Exception in thread "app-thread" java.lang.IllegalStateException: call was cancelled
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at io.grpc.internal.ClientCallImpl.halfClose(ClientCallImpl.java:419)
	at io.grpc.ForwardingClientCall.halfClose(ForwardingClientCall.java:47)
	at io.grpc.ForwardingClientCall.halfClose(ForwardingClientCall.java:47)
	at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onCompleted(ClientCalls.java:330)
	at com.salesforce.reactivegrpc.common.ReactivePublisherBackpressureOnReadyHandler.onComplete(ReactivePublisherBackpressureOnReadyHandler.java:131)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:136)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.onComplete(FluxTakeUntilOther.java:236)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilOtherSubscriber.onComplete(FluxTakeUntilOther.java:112)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilOtherSubscriber.onNext(FluxTakeUntilOther.java:94)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:808)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:892)
	at reactor.core.publisher.ReplayProcessor.onNext(ReplayProcessor.java:436)
	at reactor.core.publisher.MonoProcessor.drainLoop(MonoProcessor.java:504)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:347)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.cancel(FluxDoFinally.java:145)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.cancel(FluxFlattenIterable.java:271)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1497)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1466)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1278)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1497)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1466)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1278)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.cancel(FluxRetryWhen.java:123)
	at reactor.core.publisher.SerializedSubscriber.cancel(SerializedSubscriber.java:147)
	at reactor.core.publisher.Operators.terminate(Operators.java:642)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.cancel(MonoFlatMapMany.java:121)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.cancelMain(FluxTakeUntilOther.java:173)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.cancel(FluxTakeUntilOther.java:190)
	at reactor.core.publisher.SerializedSubscriber.cancel(SerializedSubscriber.java:147)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.cancel(FluxPublishOn.java:265)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:135)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:389)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:473)
	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:166)
```
One of my own subscribers throws an exception which is caught in
```
at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:135)
```
Before LambdaSubscriber propagates the error downstream, it calls cancel() on the subscription. That cancel() call throws the problematic exception.

I think the interesting part is here:
```
at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onCompleted(ClientCalls.java:330)
at com.salesforce.reactivegrpc.common.ReactivePublisherBackpressureOnReadyHandler.onComplete(ReactivePublisherBackpressureOnReadyHandler.java:131)
````
ReactivePublisherBackpressureOnReadyHandler calls CallsStreamObserver.onCompleted() (should not throw exception because the javadoc does not state so?). CallStreamObserver calls ClientCall.halfClose(), which is documented:
```
void io.grpc.ClientCall.halfClose()

Close the call for request message sending. Incoming response messages are unaffected. This should be called when no more messages will be sent from the client.
Throws:IllegalStateException - if call is already halfClose()d or canceled
```
I'm not sure should grpc not throw this exception at all or improve the documentation on CallsStreamObserver.onCompleted(). I think reactive-grpc should catch the exception anyway?

**Comment by tukez** [comment]
Also, some bits from reactivestreams spec:
https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.2/README.md#user-content-2.13
```
Calling onSubscribe, onNext, onError or onComplete MUST return normally except when any provided parameter is null in which case it MUST throw a java.lang.NullPointerException to the caller, for all other situations the only legal way for a Subscriber to signal failure is by cancelling its Subscription. In the case that this rule is violated, any associated Subscription to the Subscriber MUST be considered as cancelled, and the caller MUST raise this error condition in a fashion that is adequate for the runtime environment.
```
https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.2/README.md#user-content-3.15
```
Calling Subscription.cancel MUST return normally.
```

**Comment by rmichela** [comment]
Sounds reasonable. Some of the subtle spec mismatches between gRPC and Reactive have been tricky to find.

Can you provide a test program that reproduces the problem? That would make fixing significantly easier. 😁
