### ISSUE TITLE
Receive UNKNOWN: Exception was thrown by handler

### ISSUE THREAD

**Issue by OlegZhilo** [salesforce/reactive-grpc#91]
### Version lib
Version: 0.8.2

I'm using BI stream on Android. 
Channel: 
OkHttpChannelBuilder.forAddress(host, port)
                .intercept(metadataClientInterceptor, grpcLoggingInterceptor)
                .build()
But after get first bunch of values, I get UNKNOWN: Exception was thrown by handler

My ios colleagues have same problem. But they have solved it by using:
https://github.com/grpc/grpc/blob/master/src/objective-c/RxLibrary/GRXBufferedPipe.m

What am I doing wrong?
```

io.grpc.StatusRuntimeException: UNKNOWN: Exception was thrown by handler.
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
        at com.trading.interactor.common.grpc.GrpcLoggingInterceptor$interceptCall$1$start$1.onClose(GrpcLoggingInterceptor.kt:51)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

```

**Comment by OlegZhilo** [comment]
https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlClient.java

How to use flow-controll with your library?

**Comment by rmichela** [comment]
Judging by your stack trace and [error message](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L340), I suspect your server is experiencing an unhandled exception.

You don't directly manage flow control with Reactive gRPC. The library manages the flow control for you.

**Comment by OlegZhilo** [comment]
@rmichela I found this message in grpc repo
https://github.com/grpc/grpc/blob/b74e050112fbdcb2cfdf475a167aa326e9bf26b9/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs
line 340

Could it to explain why error is  happens?

**Comment by revers-back** [comment]
@rmichela we have investigated that without using genereted by rxgrpc stub the stream works fine. Here is code using only grpc generated code, stream works fine
```
    fun subscribeCandles(securityId: Int,
                         candlePeriod: CandlePeriod): Observable<CandleEvent> {
        
        val request = CandleRequest.newBuilder()
                .setSubscribe(CandleSubscribeRequest.newBuilder()
                        .setSecurityId(securityId)
                        .setPeriodValue(candlePeriod.seconds)
                        .build()).build()
        
        val responseProcessor = PublishProcessor.create<CandleEvent>()

        val rawRequest = MarketDataServiceGrpc.newStub(channel).openCandlesStream(object :StreamObserver<CandleEvent> {
            override fun onNext(value: CandleEvent?) {
                Logger.e("subscribeCandles onNext $value")
                responseProcessor.onNext(value)
            }

            override fun onError(t: Throwable?) {
                Logger.e("subscribeCandles error $t")
                responseProcessor.onError(t)
            }

            override fun onCompleted() {
                responseProcessor.onComplete()
                Logger.e("subscribeCandles onCompleted")
            }
        })
        
        rawRequest.onNext(request)

        return responseProcessor.toObservable()
    }
```
Thid code is using rx generated stubs, with this the error described above occurs
```
    fun subscribeCandles(securityId: Int,
                         candlePeriod: CandlePeriod): Observable<CandleEvent> {
        
        val request = CandleRequest.newBuilder()
                .setSubscribe(CandleSubscribeRequest.newBuilder()
                        .setSecurityId(securityId)
                        .setPeriodValue(candlePeriod.seconds)
                        .build()).build()
        
        return client.openCandlesStream(Flowable.just(request)).toObservable()
    }
```
the proto for the method looks like this 
`rpc OpenCandlesStream (stream CandleRequest) returns (stream CandleEvent) {}
`
It's seems that one of the constructions in 
`com.salesforce.rxgrpc.stub.ClientCalls#manyToMany`
producing the problem. Any suggestion where to dig?

**Comment by rmichela** [comment]
I would start by debugging your server. Why is it throwing an error when the request is made using the RxJava bindings? How do the two different implementations differ over the wire, and how are they processed by gRPC on the server?

I believe you are using C# on the server. I haven't tested interoperability with the C# server implementation. Perhaps I'm subtly doing something wrong in RxGrpc that the Java server is OK with, but the C# server is not. 😕

**Comment by revers-back** [comment]
Well, the server is c# written, but we don't have access to it, only endpoint. We have asked server side, but thet did't find any errors in logs. We will try to find some solution, thanks for reply.

**Comment by rmichela** [comment]
Hmm... The error message in the initial report points to an exception on the server, but the server swallows it. You should see something like "Exception occurred in the handler or an interceptor." in the server logs.

https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L263-L267

**Comment by rmichela** [comment]
@OlegZhilo @revers-back Any progress on this issue?

**Comment by OlegZhilo** [comment]
@rmichela Unfortunetly no... We are still trying find out it.

**Comment by rmichela** [comment]
I'm going to close this issue. Please re-open if you find out what caused your problem.
